In [17]:
input1={'name':'nagadurga',
        'accountnumber':'5000457858',
        'credit_type':'credit',
        'location':'metro',
        'amount':100000,
        'employment_type':'salaried',
       'age':22
       }

In [1]:
input1={'name':'nagadurga',
        'accountnumber':'5000457858',
        'credit_type':'debit',
        'location':'metro',
        'amount':100000,
        'employment_type':'salaried',
       'age':22
       }

In [14]:
def banking_example(bankdetail):
    bnagadurga_bal=100000
    
    if input1['name']=='nagadurga':
        if input1['credit_type']=='credit':
            if input1['location']=='metro':
                dis=input1['amount']*.10
                
                balance=bnagadurga_bal+input1['amount']+dis
                if input1['employment_type']=='salaried':
                    balance=balance+0
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
                        
                elif input1['employment_type']=='individual':
                    balance=balance+10000
                    if input1['age']>40:
                        balance=balance+18000
                    elif input['age']<=40:
                        balance=balance
                        
                elif input1['employment_type']=='business':
                    balance=balance+500
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
            elif input1['location']=='nonmetro':
                dis=input1['amount']*.05
                balance=bnagadurga_bal+input1['amount']+dis
                
                if input1['employment_type']=='salaried':
                    balance=balance+0
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
                        
                elif input1[employment_type]=='individual':
                    balance=balance+1000
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
                
                elif input1['employment_type']=='business':
                    balance=balance+500
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
                    
        elif input1['credit_type']=='debit':
            if input1['location']=='metro':
                dis=input1['amount']*.10
                
                balance=bnagadurga_bal+input1['amount']-dis
                if input1['employment_type']=='salaried':
                    balance=balance+0
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
                        
                elif input1['employment_type']=='individual':
                    balance=balance+10000
                    if input1['age']>40:
                        balance=balance+18000
                    elif input['age']<=40:
                        balance=balance
                        
                elif input1['employment_type']=='business':
                    balance=balance+500
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
            elif input1['location']=='nonmetro':
                dis=input1['amount']*.05
                balance=bnagadurga_bal+input1['amount']-dis
                
                if input1['employment_type']=='salaried':
                    balance=balance+0
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
                        
                elif input1[employment_type]=='individual':
                    balance=balance+1000
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
                
                elif input1['employment_type']=='business':
                    balance=balance+500
                    if input1['age']>40:
                        balance=balance+18000
                    elif input1['age']<=40:
                        balance=balance
                        
    return {'name':input1['name'],
            'accountnumber':input1['accountnumber'],
            'credit_type':input1['credit_type'],
            'location':input1['location'],
           'amount':input1['amount'],
            'employment_type':input1['employment_type'],
           'age':input1['age'],
           'balance':balance}

In [15]:
banking_example(input1)

{'name': 'nagadurga',
 'accountnumber': '5000457858',
 'credit_type': 'credit',
 'location': 'metro',
 'amount': 100000,
 'employment_type': 'salaried',
 'age': 22,
 'balance': 210000.0}

In [46]:
input2={'name':'dhanalakshmi',
        'accountnumber':'5001457858',
        'credit_type':'credit',
        'location':'non_metro',
        'amount':200000,
        'employment_type':'individual',
       'age':35
       }

In [47]:
def banking_example2(bankdetail):
    bdhanalakshmi_bal=100000
    
    if input2['name']=='dhanalakshmi':
        if input2['credit_type']=='credit':
            if input2['location']=='metro':
                dis=input2['amount']*.10
                balance=bdhanalakshmi_bal+input2['amount']+dis
                
                if input2['employment_type']=='salaried':
                    balance=balance+0
                    
                    if input2['age']>40:
                        balance=balance+18000
                        
                    elif input2['age']<=40:
                        balance=balance
                        
                elif input2['employment_type']=='individual':
                    balance=balance+1000
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance       
                        
                elif input2['employment_type']=='business':
                    balance=balance+500
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance              
            elif input2['location']=='non_metro':
                dis=input2['amount']*.05
                balance=bdhanalakshmi_bal+input2['amount']+dis
                
                if input2['employment_type']=='salaried':
                    balance=balance+0
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance
                        
                elif input2['employment_type']=='individual':
                    balance=balance+1000
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance       
                        
                elif input2['employment_type']=='business':
                    balance=balance+500
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance                 
                    
        elif input2['credit_type']=='debit':
            if input2['location']=='metro':
                dis=input2['amount']*.10
                balance=bdhanalakshmi_bal+input2['amount']-dis
                
                if input2['employment_type']=='salaried':
                    balance=balance+0
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance
                        
                elif input2['employment_type']=='individual':
                    balance=balance+1000
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance       
                        
                elif input2['employment_type']=='business':
                    balance=balance+500
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance              
            elif input2['location']=='non_metro':
                dis=input2['amount']*.05
                balance=bdhanalakshmi_bal+input2['amount']-dis
                if input2['employment_type']=='salaried':
                    balance=balance+0
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance
                        
                elif input2['employment_type']=='individual':
                    balance=balance+1000
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance       
                        
                elif input2['employment_type']=='business':
                    balance=balance+500
                    if input2['age']>40:
                        balance=balance+18000
                    elif input2['age']<=40:
                        balance=balance                  
    return {'name':input2['name'],
            'accountnumber':input2['accountnumber'],
            'credit_type':input2['credit_type'],
            'location':input2['location'],
           'amount':input2['amount'],
            'employment_type':input2['employment_type'],
           'age':input2['age'],
           'balance':balance}

In [48]:
banking_example2(input2)

{'name': 'dhanalakshmi',
 'accountnumber': '5001457858',
 'credit_type': 'credit',
 'location': 'non_metro',
 'amount': 200000,
 'employment_type': 'individual',
 'age': 35,
 'balance': 311000.0}

In [1]:
input3={'name':'baburao',
       'accountnumber':5002457858,
       'credit_type':'debit',
       'location':'metro',
       'amount':100000,
       'employment_type':'business',
       'age':43}

In [6]:
def banking_example3(bankdetails):
    bbaburao=300000
    
    if input3['name']=='baburao':
        if input3['credit_type']=='credit':
            if input3['location']=='metro':
                dis=input3['amount']*.10
                balance=bbaburao+input3['amount']+dis
                
                if input3['employment_type']=='salaried':
                    balance=balance+0
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
                elif input3['employment_type']=='individual':
                    balance=balance+1000
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
                elif input3['employment_type']=='business':
                    balance=balance+500
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
            elif input3['location']=='non_metro':
                dis=input3['amount']*.05
                balance=bbaburao+input3['amount']+dis
                
                if input3['employment_type']=='salaried':
                    balance=balance+0
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
                elif input3['employment_type']=='individual':
                    balance=balance+1000
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
                elif input3['employment_type']=='business':
                    balance=balance+500
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
        elif input3['credit_type']=='debit':
            if input3['location']=='metro':
                dis=input3['amount']*.10
                balance=bbaburao-input3['amount']-dis
                
                if input3['employment_type']=='salaried':
                    balance=balance+0
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
                elif input3['employment_type']=='individual':
                    balance=balance+1000
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
                elif input3['employment_type']=='business':
                    balance=balance+500
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
            elif input3['location']=='non_metro':
                dis=input3['amount']*.05
                balance=bbaburao-input3['amount']-dis
                
                if input3['employment_type']=='salaried':
                    balance=balance+0
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
                elif input3['employment_type']=='individual':
                    balance=balance+1000
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                        
                elif input3['employment_type']=='business':
                    balance=balance+500
                    if input3['age']>40:
                        balance=balance+18000
                    elif input3['age']<=40:
                        balance=balance
                            
    return {'name':input3['name'],
            'accountnumber':input3['accountnumber'],
            'credit_type':input3['credit_type'],
            'location':input3['location'],
           'amount':input3['amount'],
            'employment_type':input3['employment_type'],
           'age':input3['age'],
           'balance':balance}

In [7]:
banking_example3(input3)

{'name': 'baburao',
 'accountnumber': 5002457858,
 'credit_type': 'debit',
 'location': 'metro',
 'amount': 100000,
 'employment_type': 'business',
 'age': 43,
 'balance': 208500.0}

In [15]:
input4={'name':'srinivas',
      'accountnumber':5002457858,
      'credit_type':'credit',
      'location':'metro',
      'amount':200000,
      'employment_type':'business',
      'age':24}

In [16]:
def banking_example(bankdetails):
    bsrinivas=200000
    
    if input4['name']=='srinivas':
        if input4['credit_type']=='credit':
            if input4['location']=='metro':
                dis=input4['amount']*.10
                balance=bsrinivas+input4['amount']+dis
                
                if input4['employment_type']=='salaried':
                    balance=balance+0
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
                elif input4['employment_type']=='individual':
                    balance=balance+1000
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
                elif input4['employment_type']=='business':
                    balance=balance+500
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
            elif input4['location']=='non_metro':
                dis=input4['amount']*.05
                balance=bsrinivas+input4['amount']+dis
                
                if input4['employment_type']=='salaried':
                    balance=balance+0
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
                elif input4['employment_type']=='individual':
                    balance=balance+1000
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
                elif input4['employment_type']=='business':
                    balance=balance+500
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
        elif input4['credit_type']=='debit':
            if input4['location']=='metro':
                dis=input4['amount']*.10
                balance=bsrinivas-input4['amount']-dis
                
                if input4['employment_type']=='salaried':
                    balance=balance+0
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
                elif input4['employment_type']=='individual':
                    balance=balance+1000
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
                elif input4['employment_type']=='business':
                    balance=balance+500
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
            elif input4['location']=='non_metro':
                dis=input4['amount']*.05
                balance=bsrinivas-input3['amount']-dis
                
                if input4['employment_type']=='salaried':
                    balance=balance+0
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
                elif input4['employment_type']=='individual':
                    balance=balance+1000
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                        
                elif input4['employment_type']=='business':
                    balance=balance+500
                    if input4['age']>40:
                        balance=balance+18000
                    elif input4['age']<=40:
                        balance=balance
                            
    return {'name':input4['name'],
            'accountnumber':input4['accountnumber'],
            'credit_type':input4['credit_type'],
            'location':input4['location'],
           'amount':input4['amount'],
            'employment_type':input4['employment_type'],
           'age':input4['age'],
           'balance':balance}

In [17]:
banking_example(input4)

{'name': 'srinivas',
 'accountnumber': 5002457858,
 'credit_type': 'credit',
 'location': 'metro',
 'amount': 200000,
 'employment_type': 'business',
 'age': 24,
 'balance': 420500.0}